---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: maven
    tag: "3"
inputs:
- name: cfenv
outputs:
- name: jar
run:
  path: sh
  args:
  - -exc
  - |
    cd cfenv && mvn install
    mv target/cfenv*.jar ../jar/cfenv.jar
