---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: java
    tag: 8-alpine
inputs:
- name: cfenv
outputs:
- name: jar
run:
  path: sh
  args:
  - -exc
  - |
    cd cfenv && ./mvnw install -s .mvn/wrapper/settings.xml
    mv target/cfenv*.jar ../jar/cfenv.jar
