---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"
inputs:
- name: cfenv
outputs:
- name: jar
run:
  path: sh
  args:
  - -exc
  - |
    ./mvn install
    mv target/cfenv*.jar ../jar/cfenv.jar
