---
resources:
- name: cfenv
  type: git
  source:
    uri: https://github.com/cwest/cfenv-spring
    branch: master
- name: pivotal-web-services
  type: cf
  source:
    api: http://api.run.pivotal.io
    username: {{pws-username}}
    password: {{pws-password}}
    organization: {{pws-organization}}
    space: {{pws-space}}

jobs:
- name: make-jar-not-war
  plan:
  - get: cfenv
    trigger: true
  - task: maven-install
    file: cfenv/ci/tasks/build.yml
  - put: pivotal-web-services
    params:
      path: jar/cfenv.jar
      current_app_name: cfenv-spring
      manifest: cfenv/manifest.yml