---
resources:
- name: cfenv
  type: git
  source:
    uri: https://github.com/cwest/cfenv-spring
    branch: master
- name: pivotal-cloud-foundry
  type: cf
  source:
    api: {{pcf-api}}
    skip_cert_check: true
    username: {{pcf-username}}
    password: {{pcf-password}}
    organization: {{pcf-organization}}
    space: {{pcf-space}}

jobs:
- name: make-jar-not-war
  plan:
  - get: cfenv
    trigger: true
  - task: maven-install
    file: cfenv/ci/tasks/build.yml
  - put: pivotal-cloud-foundry
    params:
      path: jar/cfenv.jar
      current_app_name: cfenv-spring
      manifest: cfenv/manifest.yml